kumuluzee:
  name: api
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/postgres
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20
  openapi:
    ui:
      enabled: true
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        jndi-name: jdbc/postgres
      disk-space-health-check:
        threshold: 100000000
  priporocila:
    base-url: http://localhost:8081/v1/recommendations