kumuluzee:
  name: api
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/postgres
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20
  openapi:
    ui:
      enabled: true