kumuluzee:
  name: api
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/postgresDB
      connection-url: jdbc:postgresql://localhost:5432/postgresDB
      username: postgres
      password: postgres
      max-pool-size: 20